Swagger example file to describe hello method
---
parameters:
  - name: name
    description: Name to answer a hello
    in: path
    type: string
    required: true
responses:
  200:
    description: Json struct to say hello
    content:
      application/json:
        schema:
          type: object
          properties:
            - hello:
              type: string
            - timestamp:
              type: string
              format: date-time    